// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 2024/11/19 下午10:24:20
const configMerger = require("/Users/kevin/Documents/GitHubTanvi/koafaith/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
require("./../tailwind.config.js")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: { files: ["/Users/kevin/Documents/GitHubTanvi/koafaith/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/kevin/Documents/GitHubTanvi/koafaith/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/kevin/Documents/GitHubTanvi/koafaith/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/kevin/Documents/GitHubTanvi/koafaith/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/kevin/Documents/GitHubTanvi/koafaith/plugins/**/*.{js,ts,mjs}","/Users/kevin/Documents/GitHubTanvi/koafaith/composables/**/*.{js,ts,mjs}","/Users/kevin/Documents/GitHubTanvi/koafaith/utils/**/*.{js,ts,mjs}","/Users/kevin/Documents/GitHubTanvi/koafaith/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/kevin/Documents/GitHubTanvi/koafaith/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/kevin/Documents/GitHubTanvi/koafaith/app.config.{js,ts,mjs}"] } }));

module.exports = config
